version: '2'

services:
  app:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "diceroll.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/diceroll'
    ports:
      - '8000:8000'
  test:
    build: .
    command: >
      bash -c "py.test --cov-report term-missing --cov -vv diceroll && flake8 . --exclude __init__.py"
    environment:
      PYTHONUNBUFFERED: 'true'
    volumes:
      - '.:/diceroll'

